import { cp, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { articles } from "../content/articles.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "dist");
const repo = "series-65-exam-prep-web";
const origin = `https://mcyj.github.io/${repo}`;
const base = `/${repo}`;
const checkedAt = "2026-09-18";
const nasaaOutline = "https://www.nasaa.org/exams/general-exam-information/series-65-exam-content-outline/";
const nasaaFaq = "https://www.nasaa.org/exams/exam-faqs/";
const finraPage = "https://www.finra.org/registration-exams-ce/qualification-exams/series65";
const playUrl = "https://play.google.com/store/apps/details?id=app.mcyj.examprep.glb0001";
const supportEmail = "june1012june@gmail.com";

const escapeHtml = (value) => String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function put(path, contents) { const target = join(out, path); await mkdir(dirname(target), { recursive: true }); await writeFile(target, contents); }

function nav() {
  return `<header class="site-header"><a class="brand" href="${base}/en/"><img src="${base}/assets/app-icon.svg" width="42" height="42" alt=""><span>Series 65<br><strong>Exam Prep</strong></span></a><nav aria-label="Primary"><a href="${base}/en/guides/">Study guides</a><a href="${base}/en/faq/">FAQ</a><a href="${base}/en/support/">Support</a></nav></header>`;
}
function footer() {
  return `<footer><div><strong>Series 65 Exam Prep</strong><p>Independent study support from RushLabs. Not affiliated with or endorsed by NASAA or FINRA.</p></div><nav aria-label="Legal"><a href="${base}/en/privacy/">Privacy</a><a href="${base}/en/terms/">Terms</a><a href="${base}/en/support/">Support</a><a href="${base}/en/contact/">Contact</a></nav><p class="source-note">Official exam details checked ${checkedAt}. Confirm current rules and fees with NASAA and FINRA.</p></footer>`;
}
function layout({ title, description, path, body, type = "website", jsonLd = null }) {
  const canonical = `${origin}${path}`;
  const schema = jsonLd ? `<script type="application/ld+json">${JSON.stringify(jsonLd).replaceAll("<", "\\u003c")}</script>` : "";
  return `<!doctype html><html lang="en-US"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(title)}</title><meta name="description" content="${escapeHtml(description)}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en-US" href="${canonical}"><link rel="alternate" hreflang="x-default" href="${canonical}"><meta property="og:type" content="${type}"><meta property="og:title" content="${escapeHtml(title)}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${canonical}"><meta property="og:site_name" content="Series 65 Exam Prep"><meta name="twitter:card" content="summary"><meta name="theme-color" content="#15112d"><link rel="icon" href="${base}/assets/app-icon.svg"><link rel="stylesheet" href="${base}/assets/styles.css">${schema}</head><body><a class="skip" href="#main">Skip to content</a><div class="page-shell">${nav()}<main id="main">${body}</main>${footer()}</div></body></html>`;
}
function storeButtons(label = "Get the app") {
  return `<div class="store-block" aria-labelledby="store-heading"><p class="eyebrow" id="store-heading">${label}</p><div class="store-row"><a class="play-badge" href="${playUrl}" aria-label="Get Series 65 Prep by RushLabs on Google Play"><img src="${base}/assets/google-play-badge.png" width="194" height="75" alt="Get it on Google Play"></a><span class="store-button disabled" aria-label="Apple App Store coming soon"><span aria-hidden="true">●</span><span><small>App Store</small>Coming soon</span></span></div><p class="store-note">Available on Google Play. The iOS version is still awaiting verified publication.</p></div>`;
}

const homeBody = `<section class="hero"><div class="hero-copy"><p class="eyebrow">Uniform Investment Adviser Law Examination</p><h1>Know the rule.<br><span>Read the client.</span></h1><p class="lede">Focused Series 65 practice across economics, investment vehicles, client recommendations, and laws, regulations and ethics.</p>${storeButtons()}</div><div class="phone-stage" aria-label="Series 65 practice question preview"><img src="${base}/assets/screenshots/question.png" width="393" height="852" alt="Series 65 Exam Prep practice question screen"></div></section>
<section class="proof-strip" aria-label="App and exam highlights"><div><strong>500</strong><span>independently authored practice questions</span></div><div><strong>92 / 130</strong><span>official scored-answer pass requirement</span></div><div><strong>Local-first</strong><span>progress stored on your device</span></div></section>
<section class="split section"><div><p class="eyebrow">The current exam</p><h2>Three hours. Four domains. One integrated decision.</h2><p>The official exam contains 130 scored questions and 10 unscored pretest questions. You cannot identify the pretest items, so every question deserves a reasoned answer.</p><a class="text-link" href="${base}/en/guides/exam-guide/">Read the exam guide <span aria-hidden="true">→</span></a></div><div class="exam-card"><div><span>Format</span><strong>140 total questions</strong><p>130 scored + 10 unscored · closed book</p></div><div><span>Time</span><strong>180 minutes</strong><p>Pass at 92 correct scored answers</p></div><div><span>Fee</span><strong>USD 187</strong><p>Recheck when opening an enrolment window</p></div><p class="source-note">Sources: NASAA and FINRA, checked ${checkedAt}.</p></div></section>
<section class="section"><div class="section-heading"><div><p class="eyebrow">Inside the app</p><h2>Practise, explain, then test the mix.</h2></div><p>Work through focused questions, review the reasoning and use mock exams to test selection across domains.</p></div><div class="screens"><figure><img loading="lazy" src="${base}/assets/screenshots/question.png" width="393" height="852" alt="A Series 65 practice question"><figcaption>Commit to an answer before checking.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/explanation.png" width="393" height="852" alt="A Series 65 answer explanation"><figcaption>Review why the rule or client fact matters.</figcaption></figure><figure><img loading="lazy" src="${base}/assets/screenshots/mock-exams.png" width="393" height="852" alt="Series 65 practice test list"><figcaption>Move from focused study to mixed simulation.</figcaption></figure></div></section>
<section class="section guide-preview"><div class="section-heading"><div><p class="eyebrow">Free study guides</p><h2>Build judgment, not answer memory.</h2></div><a class="text-link" href="${base}/en/guides/">Browse all 13 guides <span aria-hidden="true">→</span></a></div><div class="guide-grid">${articles.slice(0, 6).map((a, i) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${String(i + 1).padStart(2, "0")} · ${a.category}</span><h3>${a.title}</h3><p>${a.description}</p></a>`).join("")}</div></section>
<section class="section faq-teaser"><div><p class="eyebrow">Exam, then registration</p><h2>Passing is a prerequisite—not permission to practise.</h2></div><div><p>Registration and authority to conduct investment-adviser business depend on applicable state requirements. The app cannot grant or verify professional status.</p><a class="text-link" href="${base}/en/faq/">Read the FAQ <span aria-hidden="true">→</span></a></div></section>
<section class="final-cta"><h2>Make every choice explainable.</h2><p>Series 65 Prep by RushLabs is available now on Google Play.</p>${storeButtons("App availability")}</section>`;

const softwareSchema = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "Series 65 Prep by RushLabs", applicationCategory: "EducationalApplication", operatingSystem: "Android", description: "Independent Series 65 practice and mock-exam app.", url: `${origin}/en/`, downloadUrl: playUrl, publisher: { "@type": "Organization", name: "RushLabs" }, offers: { "@type": "Offer", price: "0", priceCurrency: "USD", availability: "https://schema.org/InStock" } };
const guidesBody = `<section class="page-intro"><p class="eyebrow">Study library</p><h1>Series 65 study guides</h1><p>Original preparation guidance grounded in current NASAA and FINRA information. Legal, tax and registration details can change; verify dated facts before your exam.</p></section><section class="guide-grid all-guides">${articles.map((a) => `<a class="guide-card" href="${base}/en/guides/${a.slug}/"><span>${a.category}</span><h2>${a.title}</h2><p>${a.description}</p></a>`).join("")}</section><aside class="official-source"><h2>Official information first</h2><p>Use these guides for study methods. Use NASAA and FINRA for the current outline, enrolment, fee and administration.</p><div><a href="${nasaaOutline}">NASAA exam content outline</a><a href="${finraPage}">FINRA Series 65 page</a></div></aside>`;

function articlePage(article) {
  const related = article.related.map((slug) => articles.find((item) => item.slug === slug)).filter(Boolean);
  const body = `<article class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${base}/en/">Home</a><span>/</span><a href="${base}/en/guides/">Guides</a><span>/</span><span aria-current="page">${article.category}</span></nav><header><p class="eyebrow">${article.category}</p><h1>${article.title}</h1><p class="lede">${article.description}</p><p class="article-meta">Reviewed against official sources · ${checkedAt}</p></header><div class="article-layout"><div class="article-copy">${article.body}<section class="sources"><h2>Official sources</h2><ul><li><a href="${nasaaOutline}">NASAA Series 65 Exam Content Outline</a></li><li><a href="${finraPage}">FINRA Series 65 page</a></li><li><a href="${nasaaFaq}">NASAA Exam FAQs</a></li></ul><p>Confirm current fees, enrolment, accommodation and jurisdiction-specific registration rules before acting.</p></section></div><aside class="article-aside"><img src="${base}/assets/app-icon.svg" width="88" height="88" alt="Series 65 Exam Prep icon"><h2>Practise the distinction</h2><p>Use original questions, explanations, bookmarks and mock exams in the Android app.</p><a class="status-pill live" href="${playUrl}">Available on Google Play</a></aside></div><section class="related"><p class="eyebrow">Continue studying</p><div class="guide-grid">${related.map((item) => `<a class="guide-card" href="${base}/en/guides/${item.slug}/"><span>${item.category}</span><h3>${item.title}</h3></a>`).join("")}</div></section></article>`;
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, description: article.description, datePublished: checkedAt, dateModified: checkedAt, inLanguage: "en-US", author: { "@type": "Organization", name: "RushLabs" }, publisher: { "@type": "Organization", name: "RushLabs" }, mainEntityOfPage: `${origin}/en/guides/${article.slug}/` };
  return layout({ title: `${article.title} | Series 65 Exam Prep`, description: article.description, path: `/en/guides/${article.slug}/`, type: "article", body, jsonLd: schema });
}

const faqItems = [
  ["Is this an official NASAA or FINRA app?", "No. It is independently produced by RushLabs and is not affiliated with or endorsed by NASAA, FINRA or a securities regulator."],
  ["What is the current Series 65 format?", "NASAA and FINRA list 130 scored questions plus 10 unscored pretest questions, 180 minutes, closed book and a passing requirement of at least 92 correct scored answers."],
  ["Does passing the Series 65 make me licensed?", "No. Passing normally satisfies an exam prerequisite. Registration, background review, fees and authority to conduct business depend on the applicable jurisdiction."],
  ["What does the app include?", "The current listing describes 500 independently authored questions, explanations, mock exams, bookmarks, local progress and an optional Lock Quiz."],
  ["Does the app reproduce live exam questions?", "No. It contains independently authored study material and does not claim to reproduce secured examination questions."],
  ["Do I need a RushLabs account?", "No. The current app is local-first and does not require a RushLabs account."],
  ["Is the iOS app available?", "Public iOS availability is not currently verified. The site therefore shows the App Store version as Coming soon."],
  ["Where should I verify current rules?", "Use NASAA for the current outline and exam FAQs, FINRA for enrolment and administration, and your state securities administrator for registration requirements."],
];
const faqBody = `<section class="page-intro"><p class="eyebrow">Questions & answers</p><h1>Know the boundary before you begin.</h1><p>Current exam facts, app scope and the difference between passing and registration.</p></section><section class="faq-list">${faqItems.map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join("")}</section>`;
const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqItems.map(([name, text]) => ({ "@type": "Question", name, acceptedAnswer: { "@type": "Answer", text } })) };

const privacyBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Privacy Policy</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Operator</h2><p>RushLabs operates Series 65 Exam Prep (GLB-0001). Privacy questions: <a href="mailto:${supportEmail}">${supportEmail}</a>.</p><h2>Learning information</h2><p>The current app does not require a RushLabs account. Practice answers, bookmarks, progress, review history and preferences are stored locally on your device according to the current app implementation and listing.</p><h2>Purchases</h2><p>Google Play or Apple App Store handles payment information under its own policies. RushLabs does not receive card details through the app. Store product and transaction information may be used to determine access.</p><h2>Notifications and Lock Quiz</h2><p>Lock Quiz is optional. Question text remains hidden on the lock screen until you explicitly enable the feature. Device notification controls remain available to you.</p><h2>Support messages</h2><p>If you contact support, RushLabs receives what you voluntarily send. Do not send passwords, payment details, purchase tokens, receipts or private learning backups.</p><h2>This website</h2><p>This static website does not use analytics, advertising cookies, accounts or contact forms. External destinations apply their own privacy practices.</p></article>`;
const termsBody = `<article class="policy"><p class="eyebrow">Legal</p><h1>Terms of Use</h1><p class="article-meta">Effective: September 18, 2026</p><h2>Independent study aid</h2><p>The app is an independent exam-preparation product. It is not affiliated with or endorsed by NASAA, FINRA or a regulator, and it does not reproduce secured examination questions.</p><h2>No professional authorisation</h2><p>Practice results and passing the Series 65 do not by themselves grant a licence, registration or authority to conduct investment-adviser business. Consult the applicable state securities administrator.</p><h2>Personal use and accuracy</h2><p>Use original learning material for personal study. Laws, regulations, tax rules and exam policies can change. Current official sources control over summaries in the app or website.</p><h2>Store purchases</h2><p>Purchase only from the product name, duration, enabled features and full localised price shown in the Store-backed confirmation. Manage renewal, cancellation and refund requests through the purchasing Store account. Deleting the app does not cancel a subscription.</p><h2>Support</h2><p>Contact <a href="mailto:${supportEmail}">${supportEmail}</a>. These terms do not limit rights that cannot lawfully be excluded.</p></article>`;
const supportBody = `<section class="page-intro"><p class="eyebrow">App support</p><h1>Tell us what happened.</h1><p>Include the app name, device OS, app version and a short description. Screenshots help when they contain no private information.</p><a class="primary-button" href="mailto:${supportEmail}?subject=Series%2065%20Exam%20Prep%20support">Email RushLabs support</a></section><section class="support-grid"><div><h2>Protect private information</h2><p>Do not send passwords, card information, purchase tokens, receipts or private learning backups.</p></div><div><h2>Purchases</h2><p>Use the purchasing Store account and Restore purchases where supported. Manage cancellation or refunds through the Store.</p></div><div><h2>Exam and registration</h2><p>Contact FINRA about administration, NASAA about the exam, and your state regulator about registration requirements.</p></div></section>`;
const contactBody = `<section class="page-intro contact"><p class="eyebrow">Contact</p><h1>RushLabs</h1><p>For app support, privacy questions or factual corrections:</p><a class="contact-email" href="mailto:${supportEmail}">${supportEmail}</a><p class="source-note">Do not email passwords, payment details, purchase tokens, receipts or private learning data.</p></section>`;

await rm(out, { recursive: true, force: true });
await mkdir(out, { recursive: true });
await cp(join(root, "assets"), join(out, "assets"), { recursive: true });
await cp(join(root, ".nojekyll"), join(out, ".nojekyll"));
await cp(join(root, "assets", "app-icon.svg"), join(out, "favicon.svg"));
await cp(join(root, "styles.css"), join(out, "assets", "styles.css"));
await put("index.html", `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Series 65 Exam Prep</title><meta name="description" content="Independent Series 65 practice and study guides."><meta http-equiv="refresh" content="0;url=./en/"><link rel="canonical" href="${origin}/en/"><script>location.replace('./en/')</script></head><body><main id="main"><p><a href="./en/">Continue to Series 65 Exam Prep</a></p></main></body></html>`);
await put("en/index.html", layout({ title: "Series 65 Exam Prep | Practice questions and study guides", description: "Prepare for the Series 65 with original practice questions, explanations, mock exams and source-checked study guides.", path: "/en/", body: homeBody, jsonLd: softwareSchema }));
await put("en/guides/index.html", layout({ title: "Series 65 study guides", description: "Original Series 65 study guides for the exam outline, client scenarios, investment vehicles, laws, ethics and mock exams.", path: "/en/guides/", body: guidesBody }));
for (const article of articles) await put(`en/guides/${article.slug}/index.html`, articlePage(article));
await put("en/faq/index.html", layout({ title: "FAQ | Series 65 Exam Prep", description: "Answers about the Series 65 exam, registration boundary, app scope, privacy and Store availability.", path: "/en/faq/", body: faqBody, jsonLd: faqSchema }));
await put("en/privacy/index.html", layout({ title: "Privacy Policy | Series 65 Exam Prep", description: "Privacy information for the Series 65 Exam Prep app and website.", path: "/en/privacy/", body: privacyBody }));
await put("en/terms/index.html", layout({ title: "Terms of Use | Series 65 Exam Prep", description: "Terms for Series 65 Exam Prep, independent learning content and Store purchases.", path: "/en/terms/", body: termsBody }));
await put("en/support/index.html", layout({ title: "Support | Series 65 Exam Prep", description: "Get help with Series 65 Exam Prep, purchases, local progress and app issues.", path: "/en/support/", body: supportBody }));
await put("en/contact/index.html", layout({ title: "Contact RushLabs | Series 65 Exam Prep", description: "Contact RushLabs about Series 65 Exam Prep support, privacy or factual corrections.", path: "/en/contact/", body: contactBody }));
await put("404.html", layout({ title: "Page not found | Series 65 Exam Prep", description: "The requested page could not be found.", path: "/404.html", body: `<section class="page-intro"><p class="eyebrow">404</p><h1>That page is not in this outline.</h1><p>The study guides and app information are still available.</p><a class="primary-button" href="${base}/en/">Return home</a></section>` }));
const urls = ["/en/", "/en/guides/", ...articles.map((a) => `/en/guides/${a.slug}/`), "/en/faq/", "/en/privacy/", "/en/terms/", "/en/support/", "/en/contact/"];
await put("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map((path) => `  <url><loc>${origin}${path}</loc><lastmod>${checkedAt}</lastmod></url>`).join("\n")}\n</urlset>\n`);
await put("robots.txt", `User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
console.log(`Built ${urls.length} indexable pages in ${out}`);
